# Generated by Django 5.2.8 on 2025-11-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('tempo_cadastro', models.DateField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
